### ISSUE TITLE
Como creo uno con mi bot??

### ISSUE THREAD

**Issue by Polin2711** [yosseferrazik/prite#1]
Buenas,
Como puedo poner este código para mí bot y en replit??

**Comment by KhanessKA** [comment]
Hola Polin ^^ , me alegra que te hayas interesado por mi bot , pero me temo que no es una plantilla , hay varias funciones que no funcionan sin un apikey , pase una buena tarde (si te intereso podrias darle una estrella)

**Comment by Isamir124** [comment]
Hola buenas sabes como creo un bot para discord?

**Comment by yosseferrazik** [comment]
Usa esta plantilla en mi perfil, no olvides darme una estrella si te ha servido 
https://github.com/yosseferrazik/discord-bot-template
